### ISSUE TITLE
(STDERR) Error: Cannot find module './body.html'

### ISSUE THREAD

**Issue by AjkP** [meteor/tutorials#45] opened 2016-04-01 23:26 UTC
This happens after the second step of the general tutorial (i.e. using Blaze). Note that I am running this on a Mac.

I have everything set up as the tutorial asks.

body.js gets imported fine from main.js
**client/main.js**

```
import { Meteor } from 'meteor/meteor';

// Import Local Modules
import '../imports/ui/body.js';

Meteor.startup(() => {
  // code to run on server at startup
});
```

**imports/ui/body.js**

```
import { Template } from 'meteor/templating';

import './body.html';

Template.body.helpers({
  tasks: [
    { text: 'This is task 1' },
    { text: 'This is task 2' },
    { text: 'This is task 3' },
  ],
});
```

**imports/ui/body.html**

```
<body>
  <div class="container">
    <header>
      <h1>Todo List</h1>
    </header>

    <ul>
      {{#each tasks}}
        {{> task}}
      {{/each}}
    </ul>
  </div>
</body>

<template name="task">
  <li>{{text}}</li>
</template>
```

**Comment by linshu** [comment] 2016-04-05 01:41
Yes. I got the same error on Mac like below:

```
W20160404-18:33:14.401(-7)? (STDERR)          
W20160404-18:33:14.402(-7)? (STDERR) /Users/slin/.meteor/packages/meteor-tool/.1.3.0_3.1kequoz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160404-18:33:14.402(-7)? (STDERR)                        throw(ex);
W20160404-18:33:14.402(-7)? (STDERR)                              ^
W20160404-18:33:14.408(-7)? (STDERR) Error: Cannot find module './body.html'
W20160404-18:33:14.408(-7)? (STDERR)     at require (packages/modules-runtime.js:95:19)
W20160404-18:33:14.409(-7)? (STDERR)     at meteorInstall.import.ui.body.js (import/ui/body.js:3:1)
W20160404-18:33:14.409(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160404-18:33:14.409(-7)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160404-18:33:14.409(-7)? (STDERR)     at /Users/slin/Works/meteor/examples/simple-todos/.meteor/local/build/programs/server/app/app.js:34:1
W20160404-18:33:14.409(-7)? (STDERR)     at /Users/slin/Works/meteor/examples/simple-todos/.meteor/local/build/programs/server/boot.js:283:10
W20160404-18:33:14.409(-7)? (STDERR)     at Array.forEach (native)
W20160404-18:33:14.409(-7)? (STDERR)     at Function._.each._.forEach (/Users/slin/.meteor/packages/meteor-tool/.1.3.0_3.1kequoz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160404-18:33:14.410(-7)? (STDERR)     at /Users/slin/Works/meteor/examples/simple-todos/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
```

**Comment by distalx** [comment] 2016-04-05 10:38
@AjkP the error occurs if you have named your  directory `import` instead of `imports`. try changing that.

**Comment by linshu** [comment] 2016-04-05 15:43
@distalx yes, import changed to imports does make different! Surprise, directory “imports” is a fixed constant in meteor. if that, the initialization script should create it by default, instead of asking the user to create it manually.
Thanks a lot!

**Comment by benjamn** [comment] 2016-04-05 15:54
@AjkP what's in your `.meteor/packages` file? If you don't see this line, try adding it:

```
blaze-html-templates    # Compile .html files into Meteor Blaze views
```

**Comment by AjkP** [comment] 2016-04-05 21:49
@distalx in my original comment I mention:

> imports/ui/body.html

Also the fact that body.js gets imported fine is a hint at the folder name being fine.

@benjamn This is my .meteor/packages:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)
```

blaze-html-templates is there unfortunately.

Here is the full STDERR:

```
=> Exited with code: 8
W20160405-14:47:11.662(-7)? (STDERR)
W20160405-14:47:11.663(-7)? (STDERR) /Users/myuser/.meteor/packages/meteor-tool/.1.3.0_3.1kequoz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160405-14:47:11.663(-7)? (STDERR)                            throw(ex);
W20160405-14:47:11.663(-7)? (STDERR)                                  ^
W20160405-14:47:11.663(-7)? (STDERR) Error: Cannot find module './body.html'
W20160405-14:47:11.664(-7)? (STDERR)     at require (packages/modules-runtime.js:95:19)
W20160405-14:47:11.664(-7)? (STDERR)     at meteorInstall.imports.ui.body.js (imports/ui/body.js:3:1)
W20160405-14:47:11.664(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160405-14:47:11.664(-7)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160405-14:47:11.664(-7)? (STDERR)     at meteorInstall.server.main.js (server/main.js:4:1)
W20160405-14:47:11.664(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160405-14:47:11.664(-7)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160405-14:47:11.664(-7)? (STDERR)     at server/main.js:6:1
W20160405-14:47:11.664(-7)? (STDERR)     at /project/myproject/chixam-meteor/.meteor/local/build/programs/server/boot.js:283:10
W20160405-14:47:11.664(-7)? (STDERR)     at Array.forEach (native)
```

**Comment by NicoLedwith** [comment] 2016-04-15 01:41
Not sure why, but adding in `<body></body>` tags to `main.html` solves this problem

**Comment by meladawy** [comment] 2016-04-21 20:43
I confirm having the same issue in mac osx

**Comment by tcguy** [comment] 2016-04-21 21:57
I was getting a blank page with "Error: Cannot find module '../imports/ui/body.js'" in the console.  This is fixed by changing the tutorial reference to `import '../client/imports/ui/body.js';`
Not sure why the tutorial code doesn't work but I hope this helps someone.

**Comment by amm54** [comment] 2016-04-25 11:00
Confirm having the same issue in mac osx.  
You may want to try replacing import with require in body.js - worked for me:  
//import './body.html';
 require('./body.html');

**Comment by mescalina** [comment] 2016-05-19 17:47
Did you find a solution? Same issue on Ubuntu

**Comment by ramk18** [comment] 2016-05-21 05:47
Ran into the same issue in mac. 
1) Naming of imports folder is not the problem
2) Adding <body> tag in main.html did not help
3) Using require instead of import did not help

`
W20160521-11:03:00.777(5.5)? (STDERR)                       throw(ex);
W20160521-11:03:00.778(5.5)? (STDERR)                             ^
W20160521-11:03:00.788(5.5)? (STDERR) Error: Cannot find module './body.html'
W20160521-11:03:00.789(5.5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:78:1)
W20160521-11:03:00.789(5.5)? (STDERR)     at meteorInstall.imports.ui.body.js (imports/ui/body.js:3:1)
W20160521-11:03:00.789(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160521-11:03:00.789(5.5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160521-11:03:00.789(5.5)? (STDERR)     at meteorInstall.server.main.js (server/main.js:3:1)
W20160521-11:03:00.790(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160521-11:03:00.790(5.5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160521-11:03:00.791(5.5)? (STDERR)     at server/main.js:5:1
W20160521-11:03:00.791(5.5)? (STDERR)     at /Users/ramk/Workspace/simple-todos/.meteor/local/build/programs/server/boot.js:283:10
W20160521-11:03:00.791(5.5)? (STDERR)     at Array.forEach (native)`

**Comment by ramk18** [comment] 2016-05-21 05:58
Works now! My bad! Was modifying the wrong file.
@AjkP  the main.js you have used is server/main.js
Use client/main.js

**Comment by mescalina** [comment] 2016-05-21 10:43
It was the same for me, but I didn't come back to write it here cause I thought that it was too embarassing :)

**Comment by AjkP** [comment] 2016-05-23 04:54
@ramk18 @Mescalina  Seems like I had the same issue.
I'll blame it on the tutorial though 😛 . Closing issue.

**Closed as completed** 2016-05-23 04:54 UTC

**Comment by qizhang8** [comment] 2016-05-25 08:08
Can anybody provide a little more illustration on this? 
I had the same issue but I could not catch how people finally fix this.

**Comment by mitch15** [comment] 2016-05-26 12:38
@qizhang8 have you got the blaze-html-templates package added? I ran into this problem as well (not on this tutorial, in another project) and adding this solved the it for me. Make sure you're modifying the correct main.js file as well which is in the client folder, not the server.

**Comment by qizhang8** [comment] 2016-05-27 00:49
Hi, Mitch

According to your comments, I checked my code again. Indeed, I wrongly
imported the body.js from the server/main.js.

After I moved it to client/main.js, it works like a charm.

Thanks a lot for your reply!

**Comment by massanchik** [comment] 2016-05-27 22:41
### Recap for "simple-todos" totorial.

Ensure that:
- import statement in client/main.js
- blaze-html-templates installed
- imports folder typed correctly
- import statement typed correctly. Should be '../imports/ui/body.js' not './imports/ui/body.js', like in my case

**Comment by vinayaksuresh** [comment] 2016-07-24 04:00
Thanks a lot everyone!!!

**Comment by Hamidreza-Sedigh** [comment] 2016-11-01 08:27
I had the same problem. I typed meteor list and blaze-html-template was installed but I reinstalled it, it got fixed I don't know why ( it didn't work until I re run the meteor)

**Comment by abstractmatter** [comment] 2016-11-03 10:25
Had this issue: everything was running smooth, but at one point **importing any new template** in imports/ui/pages was throwing **Error: Cannot find module**

This solved the issue:

`meteor remove blaze-html-templates`
`meteor add blaze-html-templates`

Yummy :(

**Comment by addeeandra** [comment] 2016-11-12 09:10
I had this issue. Restarting the server by running **meteor** again was solved the issue.
If your **meteor** is running, stop it.
Run **meteor** again.

I don't know why this happen.

**Comment by DiegoOlivierFernandezPons** [comment] 2016-11-12 13:29
I just had this same issue. It seems due to improper file names (either by mistake or because they were renamed and Meteor hasn't noticed). Meteor doesn't notice the files have been renamed until you restart it, which is why it seems to be generating confusion.

**Comment by ghost** [comment] 2017-03-02 14:34
Im still having this issue

**Comment by abernix** [comment] 2017-03-21 14:30
I think the solution to this is mentioned in https://github.com/meteor/tutorials/issues/45#issuecomment-220760765 and this is ultimately the same as #30.  We will make this more clear! :)

**Comment by greggman** [comment] 2017-10-26 10:26
So frustrating.

none of the solutions are working for me

* tried reinstalling blaze-html-templates
* tried restarting meteor
* yes it's `imports` not `import` for the folder name
* body.js is clearly getting imported

**Comment by bvanhou** [comment] 2018-04-20 02:43
Any updates?

**Comment by ghost** [comment] 2018-04-20 21:55
Personally I just gave up on Meteor. Perhaps it was my fault, but the issues I ran in to were too many. Thankfully I wasn't too far into the project.

**Comment by jorisroling** [comment] 2018-07-24 22:42
Isn't it the problem of importing a html file is not supported on the server? Many React projects have SSR turned on.

So if you'd say:
```javascript
if (Meteor.isClient) {
  import './template.html'
}
```
It solves the issue (more or less)?
Worked for me!

**Comment by msavin** [comment] 2018-12-12 14:22
Deleting the file and recreating it has worked for me. Perhaps a file system issue.

**Comment by COScholl** [comment] 2018-12-30 18:59
> Isn't it the problem of importing a html file is not supported on the server? Many React projects have SSR turned on.
> 
> So if you'd say:
> 
> ```js
> if (Meteor.isClient) {
>   import './template.html'
> }
> ```
> 
> It solves the issue (more or less)?
> Worked for me!

As soon as I tried this logic, my application was no longer able to find template.html. I don't understand why importing the html file would be the issue. Can you elaborate?

**Comment by COScholl** [comment] 2018-12-30 19:00
> Deleting the file and recreating it has worked for me. Perhaps a file system issue.

Can you be more specific regarding which file you deleted and recreated?

**Comment by msavin** [comment] 2018-12-30 19:57
The file that Meteor could not find. I've heard that macOS sometimes locks
the files or something, if true, maybe that's the problem.

**Comment by aga98mtl** [comment] 2019-01-17 18:53
I'm facing the same problem on MacOS. Tried all the solutions in here to no avail.

**Comment by victor-3wp** [comment] 2019-03-05 15:03
I had the same problem, none of the above solution worked for me.
What worked for me after i had tried all the above was
 
- don't name the template "body", it causes conflicts in the Meteor build system
- change `<template name= "body "></template> ` to `<template name= "app_body "></template>`

Hope this helps

**Comment by evolross** [comment] 2020-01-28 00:55
I just pounded my head for a whole day with this same problem while converting an older "all global" style project to full ES6 import/export _without_ using an `imports` folder. The first loaded JS template was throwing an error `Cannot find module './layout.html'` on the _server_ console.

After many attempts, the issue was that my older project's Blaze `router.js`that has client and server route definitions could previously safely live in the `/lib` folder which would load it on both client and server with no errors. So I mistakenly put the same file (with imports/exports added) into the new `/startup/both` folder and was trying to import the same file on both client and server.

I eventually realized the HTML errors were all the client routes trying to run on the server. Duh. So I just made two `router.js` files, one for client, one for server. Put the client routes in the client file and the server routes (webhooks, form processing from landing pages, etc.) in the server folder. 

If the server console is complaining about HTML files not loading, your structure isn't right. It's confusing because the Meteor console previously reported a lot of client errors. But now using the new ES6 structure, the client errors are mostly reported in the browser console. Not the Meteor console.

**Comment by vladbalan** [comment] 2020-04-17 07:21
In my case this was caused by badly formatted html in the file that I was trying to import (i.e. `<li><span>some text</span></span>`). 

This was a template that was a part of a meteor package, so what saved me was adding it to `package.js` via `api.addFiles` instead of importing it from it's corresponding js file. This exposed the actual error and allowed me to fix it. 

Very strange and annoying, hopefully this will help others in this same situation.

**Comment by blossom-babs** [comment] 2021-05-11 13:04
> In my case this was caused by badly formatted html in the file that I was trying to import (i.e. `<li><span>some text</span></span>`).
> 
> This was a template that was a part of a meteor package, so what saved me was adding it to `package.js` via `api.addFiles` instead of importing it from it's corresponding js file. This exposed the actual error and allowed me to fix it.
> 
> Very strange and annoying, hopefully this will help others in this same situation.

I spent the last hour trying to figure out why a page that ran perfectly suddenly couldn't be found. This comment helped me realize I didn't close the span tag properly. Ugh! thanks
