### ISSUE TITLE
Copy&Paste of Tutorial Code Inserts Additional Blank Lines

### ISSUE THREAD

**Issue by ghost** [meteor/tutorials#112] opened 2017-03-14 20:17 UTC
As an example:

https://www.meteor.com/tutorials/react/testing

Copy some code & paste it into an editor (windows 10, Firefox 52)

the result is like this:

```


/* eslint-env mocha */

 

import { Meteor } from 'meteor/meteor';

import { Random } from 'meteor/random';

 

import { Tasks } from './tasks.js';

 

if (Meteor.isServer) {

  describe('Tasks', () => {
```

**Comment by abernix** [comment] 2017-03-20 09:44
Duplicate of #62.

**Closed as completed by abernix** 2017-03-20 09:44 UTC
