### ISSUE TITLE
Update Tutorial re Android on Windows

### ISSUE THREAD

**Issue by ghost** [meteor/tutorials#106] opened 2017-03-12 22:20 UTC
the tutorial page

https://www.meteor.com/tutorials/react/running-on-mobile (step06.md)

does not mention that android works on windows. On my side, those 2 steps did the work:

```shell
$ meteor npm install -g is-property
$ meteor run android
```

Java & Android SDK was already installed on my windows 10 machine. After waiting a few minutes, the todo app appeared on the android emulator.

The tutorial should be updated, to avoid more users falling into this trap. It makes a **very negative** impression (for Meteor).

**Comment by abernix** [comment] 2017-03-20 17:00
It doesn't explicitly mention that Android works on Windows, but the other options both say "Mac Only" for a reason (in other words, things are expected to work on Windows if they aren't explicitly tagged as "Mac Only").  There was a bug, https://github.com/meteor/meteor/issues/7358, affecting some Windows users, but I believe this is fixed or will be fixed soon.  I'd rather we not put this explicitly in the tutorial at the moment (especially since the work-around is frequently more complicated than this), and I'm going to try to resolve that bug today if I can reproduce it.

If there is a bug here, it's ultimately a bug with Meteor and it's already documented, so closing.

**Closed as completed by abernix** 2017-03-20 17:00 UTC

**Comment by MaksimKlepikov** [comment] 2017-03-21 19:46
`meteor npm install -g is-property `
is work for me (win10)

**Comment by kmullings** [comment] 2017-07-03 20:07
@kevrat 's solution at https://github.com/meteor/tutorials/issues/106#issuecomment-288196457 got me past this error. I first started by upgrading from 1.2.1 to 1.5.

Now I get the following errors:

✗ Android target: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment
  variable.
✗ Gradle: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
  Looked here: C:\Users\Keno Mullings\AppData\Local\Android\sdk\tools\templates\gradle\wrapper
