### ISSUE TITLE
Angular tutorial step 2.4 missing clarification

### ISSUE THREAD

**Issue by aws910** [meteor/tutorials#69] opened 2016-06-03 09:10 UTC
Thanks for being part of such a great software product and taking the time to create the tutorials for it.  My query was regarding step 2.4 of the angular tutorial, in the code snippet following the text "Let's create a template for todosList component.".  It doesn't say exactly how to "create a template".... and the filename mentioned doesn't give any clues as to how it gets there: "imports/components/todosList/todosList.html"  These directories were not listed in the first section ("all of the files that a Meteor app needs").  I have no problem creating the directories (and file), but it would be nice to be told that I have to do this, and why the directory structure needs to be this way.  I thought there might be a command to automatically create all these files, but my lack of this specific knowledge was why I attempted the tutorials in the first place.  

I browsed the change history of this tutorial page and noticed that this verbiage has changed several times - the last change of it was from "Now let's create a simple Angular list repeater", which doesn't make a lot of sense either.  Maybe this tutorial is for users more advanced than myself?

**Comment by Cramertech** [comment] 2016-07-23 17:38
I too found this to be confusing.  I just need clarification on why the directory structure is missing.  My app doesn't work and I've typed it out exactly as shown and quadruple quadruple checked it!  I think something's wrong!

I tried looking at the browser console and it says it can't find the template - which I again - quadruple quadruple checked and it's exactly where it's supposed to be.  Even tried prepending ../ to the path... that still doesn't work.

What exactly am I missing here? - I figured it out: original tutorial code is missing the /  - found that in another github issue that explained the fix and problem.  You guys really need to quality check the code before making it live.  Sheesh

**Comment by ghost** [comment] 2016-09-10 13:18
When installing, I put my big hope to this powerful frameworks, but rather disappointed when got the same problem as woohoowebs and aws90.

**Comment by decadeofdata** [comment] 2016-10-21 13:03
Yeah this tutorial is less obvious for people that havent done other tutorials before.
If you look to the left, this my folder structure that worked for me.
![angulartutorial](https://cloud.githubusercontent.com/assets/12573383/19599136/69e9998a-979f-11e6-8607-0c60cca7a8ca.png)

**Comment by lazaridis-com** [comment] 2017-03-15 20:45
@abernix - **listen** to those users and react(!).

This is a duplicate of #53 and affects #109

@hwillson - can be closed (the above 2 issues cover this issue)

**Comment by abernix** [comment] 2017-03-20 13:38
Resolved via above issues #53 and #109.

**Closed as completed by abernix** 2017-03-20 13:38 UTC
