### ISSUE TITLE
Cannot find module './_baseClone'

### ISSUE THREAD

**Issue by sztanyi** [meteor/tutorials#71] opened 2016-06-15 16:41 UTC
Following the first few steps from https://www.meteor.com/tutorials/angular/creating-an-app and face error.. module.js:338:15: Cannot find module './_baseClone'

C:\Users\Administrator\Desktop>meteor create simple-todos
Created a new Meteor app in 'simple-todos'.

To run your new app:
  cd simple-todos
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

C:\Users\Administrator\Desktop>cd simple-todos

C:\Users\Administrator\Desktop\simple-todos>meteor
[[[[[ C:\Users\Administrator\Desktop\simple-todos ]]]]]

=> Started proxy.
=> Started MongoDB.
Errors prevented isopacket load:

While loading isopacket `ddp`:
module.js:338:15: Cannot find module './_baseClone'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.w
indows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules
\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\node_mo
dules\lodash\clone.js:1:17)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load
(C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.w
indows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules
\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\lib\ind
ex.js:314:38)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load
(C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.w
indows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules
\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-template\lib\
index.js:84:43)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load
(C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.w
indows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules
\babel-plugin-transform-es2015-modules-commonjs\lib\index.js:525:46)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load
(C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object._.extend.Npm.require (C:\tools\isobuild\bundler.js:1570:22)
at Object.require (C:\tools\isobuild\bundler.js:1547:11)
at Package (packages/babel-compiler/babel-compiler.js:17:1)
at packages/babel-compiler/babel-compiler.js:356:1
at packages/babel-compiler/babel-compiler.js:356:1

=> Errors prevented startup:

   While loading plugin `compile-ecmascript` from package `ecmascript`:
   module.js:338:15: Cannot find module './_baseClone'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Administrator\AppData\Local.meteor\packages\ecmascript\0.4.4\plugi
n.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\babe
l-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\node_modules
\lodash\clone.js:1:17)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Administrator\AppData\Local.meteor\packages\ecmascript\0.4.4\plugi
n.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\babe
l-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\lib\index.js
:314:38)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Administrator\AppData\Local.meteor\packages\ecmascript\0.4.4\plugi
n.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\babe
l-plugin-transform-es2015-modules-commonjs\node_modules\babel-template\lib\index
.js:84:43)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Administrator\AppData\Local.meteor\packages\ecmascript\0.4.4\plugi
n.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\babe
l-plugin-transform-es2015-modules-commonjs\lib\index.js:525:46)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object._.extend.Npm.require (C:\tools\isobuild\bundler.js:1570:22)
   at Object.require (C:\tools\isobuild\bundler.js:1547:11)
   at Package (packages/babel-compiler/babel-compiler.js:17:1)
   at packages/babel-compiler/babel-compiler.js:356:1
   at packages/babel-compiler/babel-compiler.js:356:1

   While loading plugin `compileTemplatesBatch` from package `templating`:
   module.js:338:15: Cannot find module './_baseClone'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Administrator\AppData\Local.meteor\packages\templating\1.1.10\plug
in.compileTemplatesBatch.os\npm\node_modules\meteor\babel-compiler\node_modules\
babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\node_mod
ules\lodash\clone.js:1:17)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Administrator\AppData\Local.meteor\packages\templating\1.1.10\plug
in.compileTemplatesBatch.os\npm\node_modules\meteor\babel-compiler\node_modules\
babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\lib\inde
x.js:314:38)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Administrator\AppData\Local.meteor\packages\templating\1.1.10\plug
in.compileTemplatesBatch.os\npm\node_modules\meteor\babel-compiler\node_modules\
babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-template\lib\i
ndex.js:84:43)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Administrator\AppData\Local.meteor\packages\templating\1.1.10\plug
in.compileTemplatesBatch.os\npm\node_modules\meteor\babel-compiler\node_modules\
babel-plugin-transform-es2015-modules-commonjs\lib\index.js:525:46)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Administrator\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object._.extend.Npm.require (C:\tools\isobuild\bundler.js:1570:22)
   at Object.require (C:\tools\isobuild\bundler.js:1547:11)
   at Package (packages/babel-compiler/babel-compiler.js:17:1)
   at packages/babel-compiler/babel-compiler.js:356:1
   at packages/babel-compiler/babel-compiler.js:356:1

=> Your application has errors. Waiting for file change.

**Comment by abernix** [comment] 2017-03-20 13:54
I believe this was a temporary error at the time that this issue was opened as I cannot reproduce.  Closing, but please open a new issue if this problem persists!

**Closed as completed by abernix** 2017-03-20 13:54 UTC
