### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by Adoyle2014** [meteor/tutorials#102] opened 2017-02-09 21:06 UTC
I am using the tutorial here - https://www.meteor.com/tutorials/blaze/creating-an-app

In section 1 you are asked to use "meteor create simple-todos". You then display the directory structure that this would create, yet you reference and modify files in directories that are not present.
Example:
Section 2.2 - imports/ui/body.html
Section 3.1 - imports/api/tasks.js

Should it be "meteor create simple-todos --full" and then a display of that directory structure, or a small section on structure setup, or at least a sentence on where to add the import folder and that we should add directories in this folder as needed?

**Comment by Adoyle2014** [comment] 2017-02-09 21:11
It seems you do have the paragraph about the directory, it is just in the third section, instead of being at the end of the first or beginning of the second section.

**Comment by abernix** [comment] 2017-02-14 13:39
The `imports/*` files aren't there yet, but the beginning of the [second section](https://www.meteor.com/tutorials/blaze/templates) talks about creating the files:

> Then we create some new files in the `imports/` directory:

Would it be helpful if we suggested creating the `imports` directory first?

**Comment by Adoyle2014** [comment] 2017-02-14 13:55
Yes it would. Since section one modifies a file in the imports folder.  If more clarification is needed I will do so when not on mobile. Thanks

**Comment by abernix** [comment] 2017-02-14 18:53
Turns out this is a very common issue and a duplicate of #53.  There are even pull-requests for it.  Sorry you ran into it; someone will fix this soon!  Thank you for reporting it!

**Closed as completed by abernix** 2017-02-14 18:53 UTC
